### ISSUE TITLE
IntentService crashes when refreshing too many time.

### ISSUE THREAD

**Issue by thiagoprochnow** [thiagoprochnow/carteiradeativos#133]
IntentService crashes when refreshing too many time.

FATAL EXCEPTION: IntentService[br.com.guiainvestimento.api.service.FiiIntentService]
                                                                       Process: br.com.guiainvestimento, PID: 7026
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List br.com.guiainvestimento.api.domain.ResponseFiis.getFiiQuotes()' on a null object reference
                                                                           at br.com.guiainvestimento.api.service.FiiIntentService.addFiiTask(FiiIntentService.java:116)
                                                                           at br.com.guiainvestimento.api.service.FiiIntentService.onHandleIntent(FiiIntentService.java:55)
                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by thiagoprochnow** [comment]
commit 49caaca1c050a4b6abbc99cb615972d596003259
