### ISSUE TITLE
Force close after adding stocks with empty fields in the form

### ISSUE THREAD

**Issue by henriquenfaria** [thiagoprochnow/carteiradeativos#26]
01-29 15:53:28.890 28624 28624 E AndroidRuntime: FATAL EXCEPTION: main
01-29 15:53:28.890 28624 28624 E AndroidRuntime: Process: br.com.carteira, PID: 28624
01-29 15:53:28.890 28624 28624 E AndroidRuntime: java.lang.NumberFormatException: Invalid double: ""
01-29 15:53:28.890 28624 28624 E AndroidRuntime: 	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
01-29 15:53:28.890 28624 28624 E AndroidRuntime: 	at java.lang.StringToReal.parseDouble(StringToReal.java:267)

**Comment by henriquenfaria** [comment]
commit 0d94cdd
